### ISSUE TITLE
barrels for all fluids ?

### ISSUE THREAD

**Issue by Xerrass** [Xerrass/theMod#66]

**Comment by judos** [comment]
Had the same idea. But I think there was a mod around which does it already. I'll search for it a bit.
But still the question is: If you make it that easy to handle fluids, what is the trade-off?

**Comment by Xerrass** [comment]
probabaly more expensive recypies ? more refining processes?

**Comment by Xerrass** [comment]
oh i have it you lose some oil during fill and unfill
so put 1 oil in and only get 0.9 oil out of a barel 
what did you think ?

**Comment by judos** [comment]
Maybe a bit of both. Emptying barrels returns "dirty" ones and a small amount of liquid is lost. Maybe cleaning barrels could also return some sludge which needs to be burned like garbage or something.

**Comment by Xerrass** [comment]
interesting idea

**Comment by Muchaszewski** [comment]
Unbalanced. Pipes should have less then 100% efficency then to be worth using those over pipes on long distances. 0.5% is lost over 50 blocks eould be enough.
