### ISSUE TITLE
Fast inserter recepie automation

### ISSUE THREAD

**Issue by Muchaszewski** [Xerrass/theMod#85]
Fast inserter cannot be made anymore with Assembly Machine 2. Only in hands or in Assembly Machine 3

**Comment by Xerrass** [comment]
jep its how its suposed to be becuse of to many items needed 
probably as my mod evolves i will upgrade the slots of the assembly machine 

what did you think of an Inserter assembler ?

**Comment by Muchaszewski** [comment]
The problem is not that the fast insterer is set up this way. The problem is very fast inserter is craftable in assembly machine mk 2! I think it might be a bit of a overkill but if it would have some benefits then sure why not. Like auto engine producion inside inserter assembler so you would need only raw materials or something

**Comment by Xerrass** [comment]
yeah i will make some special assembly machines for different stuf like an Inserter assembler...

**Comment by Xerrass** [comment]
what exactly did you mean ?
did you dont want it to be produced in mk2 or what ?

**Comment by Muchaszewski** [comment]
Oh i see. Too mutch thoughts at once :p The very fast inserter is currently posible to craft with mk2, mk3 and by hand where fast inserter is only craftable in mk3 and by hand. Witch doesnt make sense. If you would do inserter assbly machine that wouldnt matter any more if they wont be craftable in standard ones any more.

**Comment by Muchaszewski** [comment]
And the idead behind inserter assembly machine is nice but it have to give some more challange to it lategame. But you will have to think about early game where you dont have power and you need inserters.

**Comment by Xerrass** [comment]
hmm ok all inserters are again producabal in the mk2
from version 0.0.7
lateron i will try to see if i get a usful idea out of an inserter assembly machine
probabaly you can produce them way faster but it uses more resources
