### ISSUE TITLE
Wrong recepie for very fast inserter

### ISSUE THREAD

**Issue by Muchaszewski** [Xerrass/theMod#86]
![image](https://cloud.githubusercontent.com/assets/5092066/10835851/ec47284c-7ea6-11e5-8648-f1b55ce457dc.png)

**Comment by Xerrass** [comment]
what happens there ?
will it need 2 times iron plates ?

**Comment by Muchaszewski** [comment]
Yes. Along with long handed inserter. And you cannot auto craft those because of that.

**Comment by Xerrass** [comment]
http://prntscr.com/8wz2p6
very fast shoud look like this

**Comment by Muchaszewski** [comment]
This is normal fast inserter.

**Comment by Xerrass** [comment]
but yeah fast longhanded and so on 
i see will be solved in version 0.0.7

**Comment by Muchaszewski** [comment]
I think xD I forgot acctualy.

**Comment by Xerrass** [comment]
you subjekt is Wrong recepie for very fast inserter

**Comment by Xerrass** [comment]
Solved in 0.0.7
